# Generated by Django 5.1.4 on 2026-09-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandelaLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='光强上限（坎德拉）')),
                ('updated_by', models.CharField(max_length=64, verbose_name='最后修改人')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '坎德拉上限',
                'verbose_name_plural': '坎德拉上限',
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_code', models.CharField(max_length=40, verbose_name='航标编号')),
                ('measured_cd', models.FloatField(verbose_name='实测光强')),
                ('required_cd', models.FloatField(verbose_name='要求光强')),
                ('bearing_error_deg', models.FloatField(verbose_name='方位偏差')),
                ('verdict', models.CharField(max_length=20, verbose_name='结论')),
                ('note', models.CharField(max_length=200, verbose_name='说明')),
                ('created_by', models.CharField(max_length=64, verbose_name='登记人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LimitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.FloatField(verbose_name='旧上限')),
                ('new_value', models.FloatField(verbose_name='新上限')),
                ('operator', models.CharField(max_length=64, verbose_name='操作者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时刻')),
            ],
            options={
                'verbose_name': '上限变更履历',
                'verbose_name_plural': '上限变更履历',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RejectedLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_code', models.CharField(max_length=40, verbose_name='灯号')),
                ('measured_cd', models.FloatField(verbose_name='所填亮度')),
                ('limit_at_rejection', models.FloatField(verbose_name='当时上限')),
                ('rejected_by', models.CharField(max_length=64, verbose_name='填写人')),
                ('rejected_at', models.DateTimeField(auto_now_add=True, verbose_name='拒绝时刻')),
            ],
            options={
                'verbose_name': '被拒灯光',
                'verbose_name_plural': '被拒灯光',
                'ordering': ['-id'],
            },
        ),
    ]
